CREATE DATABASE IF NOT EXISTS users;

CREATE USER IF NOT EXISTS 'fazt'@'%' IDENTIFIED BY 'mypassword';

GRANT ALL PRIVILEGES ON users.* TO 'fazt'@'%';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users.users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullname VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL
);
