name: Build and Push Docker Containers to ECR

on:
  push:
    branches:
      - main  # Trigger this pipeline on push to the main branch

env:
  AWS_REGION: "us-east-1"  # AWS region where ECR repository is located
  IMAGE_TAG: ${{ github.sha }}  # Use the commit hash as the image tag
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}  # AWS Account ID (stored in GitHub Secrets)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ vars.AWS_REGION }}

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build Docker images with docker-compose
      run: |
        docker-compose build

    - name: Push Docker images to ECR
      run: |
        # Loop through each service in the docker-compose.yml and push to ECR
        for service in $(docker-compose config --services); do
          # Tag the Docker image with the ECR repository URL
          docker tag $service:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service:$IMAGE_TAG
          # Push the image to ECR
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service:$IMAGE_TAG
        done

    - name: Output ECR Image URIs
      run: |
        for service in $(docker-compose config --services); do
          echo "ECR Image URI: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$service:$IMAGE_TAG"
        done
